apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console-plugin-nvidia-gpu.fullname" . }}
  labels:
    {{- include "console-plugin-nvidia-gpu.labels" . | nindent 4 }}
    app.openshift.io/runtime-namespace: {{ include "console-plugin-nvidia-gpu.name" . }}
spec:
  replicas: {{ .Values.plugin.replicas }}
  selector:
    matchLabels:
      {{- include "console-plugin-nvidia-gpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.plugin.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "console-plugin-nvidia-gpu.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.plugin.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "console-plugin-nvidia-gpu.serviceAccountName" . }}
      {{- if and (.Values.plugin.securityContext.enabled) (.Values.plugin.podSecurityContext) }}
      securityContext: {{ tpl (toYaml (omit .Values.plugin.podSecurityContext "enabled")) $ | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.plugin.image }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.plugin.imagePullPolicy }}
        {{- if and (.Values.plugin.securityContext.enabled) (.Values.plugin.containerSecurityContext) }}
        securityContext: {{ tpl (toYaml (omit .Values.plugin.containerSecurityContext "enabled")) $ | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.plugin.port }}
          protocol: TCP
        volumeMounts:
        - name: plugin-serving-cert
          readOnly: true
          mountPath: /var/cert
        - name: nginx-conf
          readOnly: true
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          {{- toYaml .Values.plugin.resources | nindent 10 }}
      volumes:
      - name: plugin-serving-cert
        secret:
          secretName: {{ include "console-plugin-nvidia-gpu.certificateSecret" . }}
          defaultMode: 420
      - name: nginx-conf
        configMap:
          name: {{ include "console-plugin-nvidia-gpu.fullname" . }}-config
          defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      {{- with .Values.plugin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plugin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plugin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
