apiVersion: v1
kind: Service
metadata:
  {{- if not .Values.plugin.certificateSecretName }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ template "console-plugin-nvidia-gpu.certificateSecret" . }}
  {{- end }}
  name: {{ include "console-plugin-nvidia-gpu.fullname" . }}
  labels:
    {{- include "console-plugin-nvidia-gpu.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.plugin.port }}-tcp
      protocol: TCP
      port: {{ .Values.plugin.port }}
      targetPort: {{ .Values.plugin.port }}
  selector:
    {{- include "console-plugin-nvidia-gpu.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
